#!/bin/bash
#
# Plugin to monitor CPU usage, for a selected set of users
#
# Usage: Place in /etc/munin/node.d/ (or link it there  using ln -s)
#        Add this to your /etc/munin/plugin-conf.d/munin-node:
#		[cpubyuser]
#		env.USERS root yann
#
#	 root and yann being a list of the users to monitor.
#	 You need to also make sure that awk is installed
#
# 2011-05-16 v 1.4 Niklas Nilsson:
#				- Rewritten to fetch a list of users based on their
#				home directory (/var/www/vhosts/ in my case)
# 
# 2008-12-08 v 1.3.1 Hanisch Elián:
#				- support for dots in user names.
#				- fix labels
#
# 2008-12-01 v 1.3 Hanisch Elián:
#				- fixes, refactoring and code cleanup
#				- Users that use cpu but aren't in the USERS env var
#				are plotted as "others", set others.graph to 'no' if
#				you	don't want this.
#
# 2008-03-20 v 1.2 fireball:	fixed minor screwup, works now ^^
#
# 2008-01-09 v 1.1 fireball:	fixed "-" in usernames, those get replaced by "_" now.
#				set usernames in config accordingly (that is with _)
#
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#

#%# family=auto
#%# capabilities=autoconf
USERS=`cat /etc/passwd | grep "/var/www/vhosts" | cut -d ":" -f1`

if [ "$1" = "autoconf" ]; then
	echo "yes"
	exit
fi


if [ "$1" = "config" ]; then
	echo "graph_args --base 1000 -r --lower-limit 0"
	echo "graph_title CPU usage per user"
	echo "graph_category system"
	echo "graph_info This graph shows CPU usage, for all VHost users"
	echo "graph_vlabel %"
	echo "graph_scale no"
	echo "graph_period second"
	_USERS=${USERS//[-.]/_}
	echo "graph_order "${_USERS/\n/ }
	FIRSTUSER=1;
	for USER in $USERS; do
		_USER=${USER//[-.]/_}
		echo "${_USER}.label $USER"
		echo "${_USER}.info CPU used by user $USER"
		echo "${_USER}.type GAUGE"
		echo "${_USER}.draw LINE1"
		if [ $FIRSTUSER -eq 1 ]; then
			echo "${_USER}.draw AREA"
			FIRSTUSER=0
		else
			echo "${_USER}.draw STACK"
		fi
	done
	exit
fi


for USER in $USERS; do
	ps -o "%C%U" -u$USER | \
	awk -v USERS="$USERS" -v USER="$USER" '
		{
			if ($2 != "USER") 
				CPU_USER[USER]+=$1
			else
				CPU_USER[USER]+=0
		}
		END {
			_user=USER
			gsub(/[-.]/,"_", _user);
			print _user".value", CPU_USER[USER]
	}'
done